### ISSUE TITLE
Merge Interop Milestone Tracking

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#2830]
Tracking issue for [Merge Interop Milestones](https://hackmd.io/@tvanepps/amphora-milestones#Milestones)

Milestones
- [X] M0: Implementation started
- [ ] M1: Upgrade to latest [spec](https://github.com/ethereum/execution-apis/blob/main/src/engine/interop/specification.md)
- [ ] M2: 1-to-1 Interop (no transition) – One EL and one CL team pair off for basic interop - [ ] - [ ] M3: 1-to-1 Interop (with transition) – One EL and one CL team pair off for full interop testing
- [ ] M4: Many-to-Many Interop – 2 or more EL and CL teams perform interop testing
- [ ] M5: All-to-All persistent devnet – All ready EL and CL teams create a long-lived devnet

**Comment by paulhauner** [comment]
Hi there :wave: I'm working on Besu interop with Lighthouse and I came across the following error:

```
2021-10-04 11:25:31.121+11:00 | vert.x-worker-thread-0 | INFO  | ExecutionEngineJsonRpcMethod | consensus JSON-RPC request engine_forkchoiceUpdated
2021-10-04 11:25:31.123+11:00 | vert.x-eventloop-thread-4 | ERROR | ExecutionEngineJsonRpcMethod | failed to exec consensus method engine_forkchoiceUpdated
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
	at org.hyperledger.besu.consensus.merge.MergeBlockProcessor$CandidateBlock.updateForkChoice(MergeBlockProcessor.java:166)
	at org.hyperledger.besu.consensus.merge.PostMergeContext.updateForkChoice(PostMergeContext.java:109)
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.engine.EngineForkchoiceUpdated.syncResponse(EngineForkchoiceUpdated.java:43)
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.ExecutionEngineJsonRpcMethod.lambda$response$0(ExecutionEngineJsonRpcMethod.java:66)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

This error was raised when Lighthouse sent a forkchoice update with the finalized block hash as 0x00..00:

```
Oct 04 11:25:31.119 INFO Issuing engine_forkchoiceUpdated        head_block_hash: 0x8ce8e58b1fa79c11850b60106dc77a680867cac09109e969eaf7a491ac7681d8, finalized_block_hash: 0x0000000000000000000000000000000000000000000000000000000000000000, service: exec
```

I had a seemingly [similar issue](https://github.com/ethereum/go-ethereum/pull/23607#issuecomment-931897512) with Geth where they couldn't process the 0x00..00 finalized block hash. Perhaps that is the issue here too?

**Comment by garyschulte** [comment]
> I had a seemingly [similar issue](https://github.com/ethereum/go-ethereum/pull/23607#issuecomment-931897512) with Geth where they couldn't process the 0x00..00 finalized block hash. Perhaps that is the issue here too?

Sorry for the slow reply.  Yes, that was it exactly, and we are playing nicely now :+1:
