### ISSUE TITLE
IBFT2 to QBFT migration

### ISSUE THREAD

**Issue by jframe** [hyperledger/besu#2991]
This feature is for migrating between the IBFT2  and the QBFT.

The migration will use a hard fork approach specifying which blocks each consensus mechanism will start from.

QBFT is the planned long term support BFT consensus algorithm, and we’d like to provide a pathway for existing networks to migrate across

- [x] Create a Switchable BesuControllerBuilder without migration capabilities #2997
- [x] Unified protocol schedule for migrating consensus mechanism #2998
- [x] Switchable protocol context for consensus migration #3000
- [x] Switchable mining co-ordinator #2999
- [x] IBFT to QBFT integration tests #3315
- [x] Allow multiple BftExecutors to be created #3004
- [x] Allow BftMiningCoordinator to be shutdown from same thread #3003
- [ ] Switchable sub-protocol manager for bft migration #3002
- [ ] Ibft2 to qbft migration single node AT #3001
- [ ] QBFT Migration: Use correct BftExtraDataCodec when validating the migration block's parent hash #3469
- [ ] QBFT migration: protocol context needs the context for block being proposed #3146
- [ ] Bft RPCs to switch and be enabled for bft migration #3009
- [ ] Migrating PluginServiceFactory - createAdditionalPluginServices #3148
- [ ] IBFT2 to QBFT migration ATs #3005

**Comment by ItayPodhajcer** [comment]
Hi @jframe @lucassaldanha ,
Haven't found any updates on this since November 2021.
Is there anything new on this migration feature?

**Comment by iamhsk** [comment]
Hi @ItayPodhajcer, thank you for your inquiry! Currently the Besu maintainers are not planning on working on this migration feature for the foreseeable future. We welcome any community contribution though 🙂

**Comment by ItayPodhajcer** [comment]
Hi @iamhsk,

This is a very disappointing answer, as IBFT 2.0 was THE way to go with Hyperledger Besu based PoA networks before QBFT reached production grade.
Expecting someone in the community with no prior experience on this codebase, to go into the heart of the consensus mechanism and implement a migration path seems highly unrealistic.

This significantly lowers the reliability of this software (and we are running three networks with it, one of them is a production network), as taking the risk that something that's being used now won't be supported in the future, and no migration path to whatever replaced that something isn't provided, isn't something that can be afforded on production workloads.

We chose Hyperledger Besu because it seemed like the best option available for a private permissioned network with enterprise capabilities, WE TOOK THE RISK, and now we are pretty much stuck with something that's very hard to upgrade, as upgrade means creating an additional network (with all the members deploying nodes to that new network in addition to the current one) and "copy" the data somehow from the existing contracts to the one in the new network.

This shouldn't happen with software that's considered ready for production!

**Comment by iamhsk** [comment]
Hello @ItayPodhajcer,

**Comment by ItayPodhajcer** [comment]
Thanks for the clarification @iamhsk!

The need to migrate was triggered by the docs leading to believe that QBFT is the long-term support consensus algorithm starting from the point it reached a production grade release.
So, to make sure we are not caught by surprise by IBFT 2.0 being retired, cause as I mentioned before, we are running three networks, one of which is a production network, we wanted to start looking at the migration path as early as possible.

Your last answer made it clear that IBFT 2.0 won't be going away that fast, and once it does, a migration path will already be available.

Thank you!

**Comment by feed755x** [comment]
@ItayPodhajcer @iamhsk https://consensys.net/docs/goquorum/en/latest/configure-and-manage/configure/consensus-protocols/qbft/ this information would work for the migration from ibft to qbft in hyperledger?

**Comment by ItayPodhajcer** [comment]
Looks pretty good!!

Two questions:
1. Why is `geth init` is required?
2. Can the transition update be done gradually and not all nodes at once if the transition block is far enough in the future?

Thanks for all your great work!!

**Comment by non-fungible-nelson** [comment]
@iamhsk - status on this?

**Comment by SimowTopos** [comment]
Hello team, any news on this feature? 
I found in this doc : https://consensys.net/blog/quorum/consensys-quorum-21-7-0-product-update-london-hard-fork-qbft-and-more/
"Because QBFT is an early access feature, we currently recommend it for new networks. Existing networks using IBFT2.0 cannot currently migrate to QBFT. This will become available in a future release. The ConsenSys Quorum team would also welcome any community feedback on the feature and their experience using it in their networks."

The link proposed by @feed755x is for Quorum consensus switch and not besu....Can we have some help on this please? Thanks

**Comment by SimowTopos** [comment]
Hello @jframe , @lucassaldanha , @iamhsk ,
I deep dived on the besu code related to this issue...mainly MigratingProtocolContext  in Besu consensys common.
In getConsensusContext : 
`@Override
  public <C extends ConsensusContext> C getConsensusContext(final Class<C> klass) {
    final long chainHeadBlockNumber = getBlockchain().getChainHeadBlockNumber();
    return consensusContextSchedule.getFork(chainHeadBlockNumber).getValue().as(klass);
  }`
We encounter a java.lang.ClassCastException when we have a genesis configuration to trigger a migration from IBFT2 to QBFT : 
`"ibft2" : {
      "blockperiodseconds" : 2,
      "epochlength" : 30000,
      "requesttimeoutseconds" : 4
    },
    "qbft": {
      "blockperiodseconds": 2,
      "epochlength": 30000,
      "requesttimeoutseconds": 10,
      "startBlock": 1520
    }`

The issue seems understandable as we try to do a downcasting from BftContext  to QbftContext ( QbftContext inherit from BftContext) which is forbiden !!

I saw also that this downcasting is due to this code :  
`/**
   * Gets fork.
   *
   * @param blockNumber the block number
   * @return the fork
   */
  public ForkSpec<C> getFork(final long blockNumber) {
    for (final ForkSpec<C> f : forks) {
      if (blockNumber >= f.getBlock()) {
        return f;
      }
    }

    return forks.first();
  }`

....which return BftContext as the Treeset is reversed....

I m trying to propose a fix but needs some help from you : 
- Changing the reversed is obviously a bad idea as it has a lot of impact ! 
- Do you think if we create a new QBftContext base on BftContext is the good solution ??

Thanks a lot for your time.
Mohamed.

Error occured : 
`2023-08-19 19:58:27.869+02:00 | BftProcessorExecutor-QBFT-0 | ERROR | EventMultiplexer | State machine threw exception while processing event \{BlockTimerExpiry{Round Identifier=ConsensusRoundIdentifier{Sequence=1520, Round=0}}\}
java.lang.ClassCastException: Cannot cast org.hyperledger.besu.consensus.common.bft.BftContext to org.hyperledger.besu.consensus.qbft.QbftContext
        at java.base/java.lang.Class.cast(Class.java:3921)
        at org.hyperledger.besu.consensus.common.bft.BftContext.as(BftContext.java:70)
        at org.hyperledger.besu.consensus.common.MigratingProtocolContext.getConsensusContext(MigratingProtocolContext.java:78)
        at org.hyperledger.besu.consensus.qbft.blockcreation.QbftBlockCreatorFactory.create(QbftBlockCreatorFactory.java:71)
        at org.hyperledger.besu.consensus.qbft.statemachine.QbftRoundFactory.createNewRoundWithState(QbftRoundFactory.java:103)
        at org.hyperledger.besu.consensus.qbft.statemachine.QbftRoundFactory.createNewRound(QbftRoundFactory.java:90)
        at org.hyperledger.besu.consensus.qbft.statemachine.QbftBlockHeightManager.startNewRound(QbftBlockHeightManager.java:291)
        at org.hyperledger.besu.consensus.qbft.statemachine.QbftBlockHeightManager.handleBlockTimerExpiry(QbftBlockHeightManager.java:126)
        at org.hyperledger.besu.consensus.common.bft.statemachine.BaseBftController.handleBlockTimerExpiry(BaseBftController.java:167)
        at org.hyperledger.besu.consensus.common.bft.EventMultiplexer.handleBftEvent(EventMultiplexer.java:65)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at org.hyperledger.besu.consensus.common.bft.BftProcessor.run(BftProcessor.java:65)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by jframe** [comment]
I've updated this ticket with the progress that we have made with this feature. Development on this is currently paused and we won't be getting back to this for a while. If you want to pick this up though, would be happy to help get you started and point you in the right direction.

Creating a new QbftContext from a BftContext could work. That is similar to the solution we were working on. The approach we were taking was to have a ProtocolContext that could switch protocol contexts when reaching the Qbft block. To do this we created a [MigratingProtocolContext](https://github.com/hyperledger/besu/blob/main/consensus/common/src/main/java/org/hyperledger/besu/consensus/common/MigratingProtocolContext.java
) and a [MigratingContext](https://github.com/hyperledger/besu/blob/main/consensus/common/src/main/java/org/hyperledger/besu/consensus/common/MigratingProtocolContext.java
) which allows switching ProtocolContexts.

There is also a [ConsensusScheduleBesuControllerBuilder](https://github.com/hyperledger/besu/blob/main/consensus/common/src/main/java/org/hyperledger/besu/consensus/common/MigratingProtocolContext.java
) that will switch consensus mechanisms at a particular block.

The general approach we took was to have components for `BesuControllerBuilder`, `ProtocolSchedule`, `ProtocolContext`, `MiningCoordinator` that could switch between consensus mechanisms. In the `BesuController` [fromGensisConfig](https://github.com/hyperledger/besu/blob/main/besu/src/main/java/org/hyperledger/besu/controller/BesuController.java#L346) if we have both IBFT2 and QBFT configured in the genesis then we create a create a ConsensusScheduleBesuControllerBuilder using the IbftBesuControllerBuilder and the QbftBesuControllerBuilder which allows for switching between the consensus mechanisms at runtime.

What's missing is changing subprotocols at the fork from the IBFT2 protocol to the QBFT protocol, edge cases around the extra data codec, RPCs and lots of testing.

**Comment by Alexander-Herranz** [comment]
Any update on IBFT2 to QBFT migration feature?

**Comment by ItayPodhajcer** [comment]
Hi @jframe,

Seeing that this feature isn't being worked on for a while now, does it mean we can assume IBFT 2.0 support isn't going anywhere anytime soon?

**Comment by macfarla** [comment]
No change from the update provided above.
