### ISSUE TITLE
Kintsugi Milestone Tracking PR

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#3006]
# Tracking issue for [Kintsugi Milestones](https://hackmd.io/@tvanepps/amphora-milestones#Milestones)

## [Milestones](https://notes.ethereum.org/@djrtwo/kintsugi-milestones#Milestones)
- [x] M0: Implementation started
- [x] M1: Implement latest spec - https://hackmd.io/@n0ble/kintsugi-spec#Execution-layer
- [x] M2: 1-to-1 Interop – One EL and one CL team pair off for basic interop
- [x] M3: Many-to-Many Interop – 2 or more EL and CL teams perform interop testing
- [x] M4: Weekly devnet – Weekly devnet for more in-depth testing
- [x] M5: All-to-All persistent testnet – All ready EL and CL teams create a long-lived devnet first week of december
- [ ] M6: Kintsugi🍵 code released – All clients release Kintsugi🍵 code for public consumption

## Building and Running Besu in Interop Mode 
* clone/fetch the [latest merge branch](https://github.com/hyperledger/besu/tree/merge-branch)
* merge consensus is gated by a flag `--Xmerge-support=true`
* Besu will run/transition from whatever consensus mechanism is defined in the genesis config file at the specified terminalTotalDifficulty
* to start besu in interop mining mode from the checked-out repo, e.g.:
```bash
git clone --recursive https://github.com/hyperledger/besu
git checkout merge
./gradlew --parallel installDist && build/install/besu/bin/besu --config-file=besu-config.toml
```

`besu-config.toml`
```toml
genesis-file="genesis.json"
data-path="besu-data"
network-id=<TBD>
rpc-http-enabled=true
rpc-http-api=["ADMIN","ETH","NET","DEBUG","TXPOOL","EXECUTION"]
host-allowlist=["*"]
rpc-http-cors-origins=["*"]
rpc-http-port=8550
Xmerge-support=true
logging="DEBUG"
```

* __PoW__ genesis config files require a consensus engine block.  Unlike geth besu does not default to ethash if there is no explicit consensus mechanism.  Besu requires the devnet genesis files to have an empty `ethash{}` entry in the config block for a PoW network.
