### ISSUE TITLE
discovery v5 support

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#4036]
- [ ] investigate how to utilise the discv5 library https://github.com/consensys/discovery
- [ ] review Teku code for how to utilise the discv5 library
- [ ] add a hidden, experimental config option --Xdiscv5-enabled default false
- [ ] implement discv5 handling 
- [ ] ensure no regression - we still need to support discv4 (this is the default for geth)
- [ ] test on testnets - start with sepolia?

**Comment by macfarla** [comment]
There are regular meetings - eg https://github.com/ethereum/pm/issues/915

**Comment by macfarla** [comment]
closing this epic
