### ISSUE TITLE
Logging improvements

### ISSUE THREAD

**Issue by daniellehrner** [hyperledger/besu#4147]
### Description
We want to improve the log file output to make it easier to understand for end users. I propose to clean up the `INFO` log level and make the target group for `INFO` the end user. 

- [ ] Remove thread and class name on the info log level. I think this does not provide any value to the end users
  - An investigation found that the default log4j configuration varies between the log source and programmatically altering the default formatting was complicated 
- [x] Show an informative configuration section at the beginning (including storage, sync mode). Take Geth as example
- [x] Move `Refreshing DNS records with enrtree` to debug or trace (in progress)
- [x] `No sync target, checking current peers for usefulness` is too spammy. It should be only logged in a fixed interval [#4794](https://github.com/hyperledger/besu/issues/4794)
- [ ] Snap sync: I think for we should output just the download progress in percent in a regular interval (eg 30s). The other output can be moved to `DEBUG`.  Geth prints an estimation how long it will take as well, which I find very useful [#4941](https://github.com/hyperledger/besu/issues/4941)
- [ ] Snap sync: Once we are downloading blocks, it would be useful to print the the age of the latest block (eg 3y10m2d) to give a better sense how far we behind we are [#4941](https://github.com/hyperledger/besu/issues/4941)
- [x] Make the log message `No sync target, checking current peers for usefulness messages` clearer or downgrade it to debug/trace [#4794](https://github.com/hyperledger/besu/issues/4794)
- [x] Add context to  message ` BackwardsSyncAlgorithm | Waiting for preconditions..` #4915

`DEBUG` and `TRACE` should not be changed for the time being, as the target group are mainly the Besu contributors. There are some extra logs that we should add:

- [ ] Add why transactions have been rejected - made a separate ticket #4914

Refer to protocol-misc # 486

**Comment by ajsutton** [comment]
I'd be cautious of only logging download progress at % intervals because you don't know how long it will take to progress and the user needs regular feedback so they don't think it's stalled.

I'd suggest a regular log line, say every 15 seconds, that gives a snapshot of the sync progress. Something like: `Syncing - Blocks: 1,000,000/10,000,000 (10%), World state: 25%, Peer count: 25`.  They may not be the exact details and there would need to be variants when progress is paused waiting for peers or waiting for info from the CL etc but that's the general idea. 

Then the logs about how the sync works could move down to debug level unless:

* they're something particularly notable (starting sync, switching between modes in sync etc)
* they're something unusual that the user should be aware of (a peer failing to respond is normal, an invalid block during long sync is probably unexpected and worth logging) or
* the user needs to take some action (out of disk space, no calls from the CL for too long etc)

**Comment by macfarla** [comment]
This PR filters the DNS refresh messages (they come from tuweni) https://github.com/hyperledger/besu/pull/4155/files

**Comment by iamhsk** [comment]
Decided not to investigate  log4j configuration issue further. Closing this issue.
