### ISSUE TITLE
Shanghai / Withdrawals Epic

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#4746]
Implement https://eips.ethereum.org/EIPS/eip-4895 and engine API changes: https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md

- [x] [DONE] shanghaiTimestamp https://github.com/hyperledger/besu/pull/4743
- [x] [DONE] Add shanghaiTimestamp to ForkId #4793
- [x] [Withdrawals Hive Tests Passing] Run Against Hive Tests https://github.com/hyperledger/besu/issues/4747
- [x] [DONE] Calculate blockValue for engine_getPayloadV2 https://github.com/hyperledger/besu/issues/4861
- [x] [DONE] Withdrawals EVM and Block changes https://github.com/hyperledger/besu/issues/4878
- [x] [DONE] Withdrawals Engine API https://github.com/hyperledger/besu/issues/4776
- [x] [DONE] Implementing wei -> gwei spec changes: https://github.com/hyperledger/besu/issues/4920
- [x] [DONE] Add withdrawals details to eth_getBlock methods - https://github.com/hyperledger/besu/issues/4808
- [x] [DONE] Shanghai Engine API Updates - https://github.com/hyperledger/besu/issues/4916
- [x] [DONE] Add getPayloadBodies and getPayloadBodiesByRangeV1 https://github.com/hyperledger/besu/issues/4787
- [x] [DONE] Withdrawal account balance overflow - https://github.com/hyperledger/besu/issues/5079
- [x] [DONE] Block value calculation may be incorrect in getPayloadV2 https://github.com/hyperledger/besu/issues/5040
- [x] [DONE] Don't Record Bad Block When Proposing - https://github.com/hyperledger/besu/issues/5058
- [x] [DONE] Withdrawals execution-spec-tests https://github.com/hyperledger/besu/issues/4934
- [x] [DONE] Withdrawals acceptance tests #5078
- [x] [DONE] Integration tests for eth_getBlock methods https://github.com/hyperledger/besu/issues/4808
- [x] [DONE] CompleteBlocksTask https://github.com/hyperledger/besu/issues/4976
- [ ] [IN PROGRESS] Clean up: Change getByBlockNumber to be getByBlockHeader #4789
- [ ] [TODO] Discuss with @daniellehrner - BadBlockManager in ProtocolSpec https://github.com/hyperledger/besu/issues/5153
- [ ] [BLOCKED?] Clean up: Remove applyMergeSpecificModifications #4788
- [ ] Remove Engine API V1s once Shanghai fork has passed?
- [ ] [TODO] Schedule Shanghai Retro!

Devnet Issues:
- [x] [INVESTIGATE] lighthouse-besu withdrawals-testnet-1 issues - https://discord.com/channels/595666850260713488/892088344438255616/1055785287885783040 (maybe fixed backwards sync bug found in hive tests)
- [x] [INVESTIGATE] prysm-besu withdrawals-testnet-1 slow syncing issue (probably no withdrawals related): prysm sends newPayload batches and only 1 FCU per batch which I suspect thrashes bonsai: https://discord.com/channels/595666850260713488/892088344438255616/1055808000864034846

Not strictly Withdrawals, but for Shanghai:
- [x] ~[TODO] Placeholder: Support Shanghai in Retesteth - https://github.com/hyperledger/besu/issues/4885~ resolved by https://github.com/hyperledger/besu/pull/4900 ?
- [x] Once Withdrawals code is merged, revisit commented code from https://github.com/hyperledger/besu/pull/4900
- [ ] Reftest cleanup related to https://github.com/hyperledger/besu/pull/4913/commits/a080bffcbab3d4cd9f9a264285f6b0c39b53a54b - discussion here https://discord.com/channels/905194001349627914/1050442708587647006/1064694693461504051

~Notes~
~- Withdrawals Prototype (and other Shanghai features) https://github.com/hyperledger/besu/pull/4818~
