### ISSUE TITLE
Change getByBlockNumber to be getByBlockHeader

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#4789]
Following https://github.com/hyperledger/besu/pull/4743

We should update all the usages we can to be getByBlockHeader and phase out getByBlockNumber.

getByBlockNumber can cause issues in a post-shanghai (TimestampSchedule-enabled) chain.

This has been intentionally separated out of #4743 so it doesn't make the PR huge, see this spike for an idea of what the changes might look like: https://github.com/hyperledger/besu/pull/4687

Another related item for clean-up:
https://github.com/hyperledger/besu/pull/4743#discussion_r1045390099

Tasks
- [x] Simple replacements of getByBlockNumber to getByBlockHeader
- [x] Create getForNextBlock (used in AbstractBlockCreator, PoWMinerExecutor and likely in BFT)
- [x] Investigate FlexiblePrivacyPrecompiledContract usage in RunnerBuilder.createPrivateTransactionObserver()
- [x] Handle Dao fork and classic fork in ProtocolScheduleBuilder
- [x] BFT sequence number usage
- [x] Change streamMilestoneBlocks to a findSchedule(Predicate) [need to fix usage in TransactionPoolFactory, RunnerBuilder]
- [x] Consider deleting getByBlockNumber usage in CombinedProtocolScheduleFactory
- [x] Fix tests to getByBlockHeader or create a test ProtocolSchedule that has getByBlockNumber inc streamMilestoneBlocks for checking milestones
- [x] ScheduleBasedBlockHeaderFunctions getBlockHeaderFunctions usage of getByBlockNumber
- [x] CheckpointSyncDownloadPipelineFactory getBlockHeaderFunctions usage of getByBlockNumber
- [x] Replace HeaderBasedProtocolSchedule with ProtocolSchedule

**Comment by gfukushima** [comment]
Partial work of the trivial replaces done here: https://github.com/gfukushima/besu/tree/replace-getByBlockNumber-by-getByBlockHeader

**Comment by siladu** [comment]
Bug found during goerli sync: https://github.com/hyperledger/besu/issues/5064
