### ISSUE TITLE
Bonsai & Blockchain Storage Improvements

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#5387]
### Description
As a Besu user, I have chosen this client for its low storage requirements and low state growth. I want to ensure that this remains true through the lifetime of a Besu validating node. I want access to either improved state reduction or new features similar to pruning/frozen data that could remove old/historical data and lower my requirements over time. 

### Acceptance Criteria
* State growth stable around ~8-10GB a week or lower
* Exploration of synergies between checkpoint sync, in-protocol deposits, and removing old data outside of subjectivity period / deposit contract logs. See #5295. 

###  To-Do
- [x] Removal of old trie logs, depending on user-specified historical block limit #5390 (might not be needed)
- [x] Moving trielog to the rockdb blob part #5866
- [ ] Receipt strategy #5767 ( Zero lead byte changes #5392, Bloom filters (?))

------ 
Let's review the following before addressing...

- [ ] Ability to freeze historical data to a flat file that I can store offline or in a slower/cheaper database #5389
- [ ] Block prune strategy #4686
- [ ] RocksDB snapshots improvements #5394
- [ ] Trie branch pruning improvements #5393
