### ISSUE TITLE
Consider new storage engine over RocksDB 

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#5400]
### Description
[RocksDB is an LSM tree DB](https://artem.krylysov.com/blog/2023/04/19/how-rocksdb-works/) which is good for write heavy workloads. Besu's storage paradigm leans heavily towards reads over writes for total IOPS. 

![image.png](https://images.zenhubusercontent.com/61d767fe8dac4210aa3d15fb/e02ccdd5-2dff-4350-b405-0044a6b5ab22)

There are likely several database solutions that would better suit our needs with better read performance tradeoffs vs Rocks. Another option to explore is a mixed database. We could combine RocksDB for write heavy tasks with another DB format, maybe B+ tree, for read heavy tasks. We may find, for example, that LSM works best for the state and account tries but B+ works best for flat database, code storage, blockchain, etc. 

### Acceptance Criteria
* Order of magnitude better read performance over RocksDB to justify the switching cost
* Minimized write performance degradation to justify the switching cost

### DB Functional Requirements
* Support for arbitrary point-in-time (or at least transaction isolation with repeatable read) based queries in order to support Bonsai

### To Do
- [ ] Determine landscape of solutions that fit our functional requirements 
- [ ] Adapt storage plug-in for most relevant solutions
- [ ] Benchmark Besu storage configurations and brief results
- [ ] Determine way forward for adoption or pass on effort

**Comment by garyschulte** [comment]
Any storage solution should support arbitrary point-in-time based queries in order to support bonsai
