### ISSUE TITLE
Changes to Besu's Defaults and Profiles in next quarterly 

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#5721]
### Context

[Discussion link](https://wiki.hyperledger.org/display/BESU/Change+to+Besu+Defaults+-+Q1+2024)

As a user, I need sensible defaults for Mainnet that reflect the reality of the client in 2023. Today, Forest and Fast sync are default. These are great for private networks, but a bad UX on Mainnet. This epic explores the change of defaults for 24.1.0 release.

Evaluate use-case-based flag / default profiles:
- Solo-Staker
  - Minimal (Mirror Teku?)  
- Institutional Staker
- RPC Provider
  - Near-head
  - Archive
- Enterprise PoA Network
- Linea operators 

### To-Do
- [ ] Full flat DB
- [ ] Data storage format --> Bonsai
    - [ ] Evaluate for Private networks (wait on Bonsai Archive work?)  
- [ ] Sync mode --> Snap? (do we want to wait for snap sync server)
    - [ ] Evaluate for private networks? (cant serve data on snap)
- [ ] Evaluate split defaults for private vs public networks `--enterprise` flag that could set sensible defaults and the legacy pool

**Comment by non-fungible-nelson** [comment]
Target 23.10.0

**Comment by non-fungible-nelson** [comment]
Reference #5390 & #5388

**Comment by siladu** [comment]
> Solo-Staker
>  - Minimal (Mirror Teku?)

I think there's two variants of minimal:
1. good peer minimal (X_SNAP)
2. bad peer minimal (X_CHECKPOINT)
