### ISSUE TITLE
Moving trielog to the rockdb blob part

### ISSUE THREAD

**Issue by jframe** [hyperledger/besu#5866]
Moving trielog to the rockdb blob part

- [x] Can we delete the data stored in the rocksDB BlobDB as this is needed for pruning #5866? 
  * docs say yes, need to verify
- [x] From #5475 BlobDB is a better choice since it reduces a lot the write amplification during compaction, with the result of faster initial sync and less wear out of the disk
- [x] Verify if pruning has an impact on performance due to compaction #5866
- [x] Test that we can upgrade to a next Besu version
- [x] Test that we can downgrade to a previous Besu version
- [x] Should we have a feature flag for this or should it be enabled by default?

Notes:
* We can't move the trie branches only the trie logs
* https://github.com/facebook/rocksdb/wiki/BlobDB
* https://github.com/hyperledger/besu/pull/5471
* https://github.com/hyperledger/besu/pull/5475

**Comment by usmansaleem** [comment]
The trielog as blobdb nodes writes less bytes during compaction (on avg and on peeks) as compared to trielog without blobdb feature:

![image](https://github.com/hyperledger/besu/assets/669527/bc2494ab-2309-46d7-a606-ad2babb3a5ad)
