### ISSUE TITLE
Validate Need for Event Queue in Kikori - More performant trielog shipping versus RPC

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#6016]
## Description
Managing fleet mode at scale and in a highly performant manner may require an event bus to correctly and accurately ship trie logs from a parent to many children. For now we rely on RPC. We may need to implement something more robust as we move this feature towards production. 

### To-Do
- [ ] Validate current RPC performance for trie log shipping (max RPS for trielog shipping on parent node) 
- [ ] Validate performance degradation on the parent node as number of children increases (especially on low block time networks like Linea) 
- [ ] Decision point about event streaming 
- [ ] Follow-on ticket for scope and implementation
