### ISSUE TITLE
Worldstate Sync Improvements: Snap-2 - PMT & Verkle Worldstate

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#6144]
## Description
As Besu looks to improve its sync, we have a moment to improve the snap protocol in a way that is forward looking, allows us to simplify our code, and improver performance of Besu sync. This epic tracks the work for developing snap server, and using the lessons learned to iterate on a Snap-2 protocol with the community in a verkle forward compatible way. We should also look 

[Nethermind Implementation](https://github.com/NethermindEth/nethermind/tree/verkle/history)
[Verkle Sync HackMd](https://hackmd.io/y3rNmxHmRQKHK7QK71NFzA)

#### Snap-2
- Compatible with PMT and forward compatible with Verkle 
- Designed with Geth and Besu FlatDB in mind

#### SnapServer
- Spec compliance on Snap-1 and forthcoming Snap-2 

#### Validator Sync
- TO SCOPE 

### To-Do
- [ ] Test and release snap-1 server as experimental flag (optional for 1 or 2 releases to gather feedback and approach core devs) 
- [ ] Spec out snap-2 
- [ ] PoC Snap-2 in Besu 
    - [ ] Test on Mainnet with Besu nodes
    - [ ] Test on Kaustinien verkle testnet  
- [ ] Iterate on Snap-2 with core devs
