### ISSUE TITLE
Implement priv_getLogs

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#628]
Implement method and basic query system (no bloom filters) 

Here is the plan:

- [x] Deprecate Private Transactions `hash`/`getHash()` #639 
- [x] Store private transaction receipts using the PMT hash as key in the storage (and tweak prig_getTransactionReceipt to use it) #645
- [x] Implement priv_getLogs method #686

**Comment by lucassaldanha** [comment]
Here is the plan:

- [ ] Deprecate Private Transactions `hash`/`getHash()`
- [ ] Store private transaction receipts using the PMT hash as key in the storage (and tweak prig_getTransactionReceipt to use it)
- [ ] Implement priv_getLogs method
