### ISSUE TITLE
Berlin Network Upgrade

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#647]
Berlin Network Upgrade, see: https://eips.ethereum.org/EIPS/eip-2070

Current list of accepted EIPs:

- [ ] [EIP-2537](https://github.com/ethereum/EIPs/pull/2537)
- [ ] [EIP-2315](https://eips.ethereum.org/EIPS/eip-2315)

May make it in:
- [ ] [EIP-2515](https://eips.ethereum.org/EIPS/eip-2515)
- [ ] [EIP-2046](https://eips.ethereum.org/EIPS/eip-2046)
