### ISSUE TITLE
EIP-7002: Execution Layer Validator Exits

### ISSUE THREAD

**Issue by lucassaldanha** [hyperledger/besu#6800]
Creating this ticket as a placeholder for all EIP-7002 related work.

Reference: https://eips.ethereum.org/EIPS/eip-7002

Initial  take on some tasks:
- [x] Update BlockBody with `exits` (#6801)
- [x] Update BlockHeader with `exits_root` (#6801)
- [x] Update `engine_getPayloadV4` and `engine_newPayloadV4` to include `exits` in the Execution Payload. (#6801)
- [x] Implement Validator Exit contract helper (#6881)
- [x] Update BlockCreator and related block creation logic to include exits from precompiled contract (#6882)
- [ ] Implement Validator Exit Contract system call #6918
- [ ] Update exits to be rendered as a "request" per EIP-7685

**Comment by lucassaldanha** [comment]
I am working on the recent updates on EIP-7002 (exits -> withdrawal request). After that I am going to have to step aside as we have pressing matters in Teku that I need to help with. 

I am going to leave this feature in a working state, however I would consider it an experimental implementation until we implement #6918.

@Gabriel-Trintinalia and I have had a few meetings re the missing piece (system calls) so he can help briefing anyone. I am also always available if needed.
