### ISSUE TITLE
Release 24.8.0 checklist

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#7474]
- [x] Confirm anything outstanding for release with other maintainers on #besu-release in Discord
- [x] Update changelog if necessary, and merge a PR for it to main
  - [ ] Notify maintainers about updating changelog for in-flight PRs 
- [ ] Optional: for hotfixes, create a release branch and cherry-pick, e.g. `release-<version>-hotfix`
  - [ ] Optional: for hotfixes, create a PR into main from the hotfix branch to see the CI checks pass
- [x] On the appropriate branch/commit, create a calver tag for the release candidate, format example: `24.8.0-RC1`
  - [x] git tag 24.8.0-RC1
  - [x] git push upstream 24.8.0-RC1
- [x] Sign-off with team; announce the tag in #besu-release in Discord
  - [x] Targeting this tag for the burn-in: https://github.com/hyperledger/besu/releases/tag/24.8.0-RC1
- [x] Consensys staff start burn-in using this tag
- [x] Seek sign off for burn-in
  - [x] Pass? Go ahead and complete the release process
  - [ ] Fail? Put a message in #besu-release in Discord indicating the release will be aborted because it failed burn-in 
- [x] Using the same git sha, create a calver tag for the FULL RELEASE, example format `24.4.0`
- [x] Using the FULL RELEASE tag, create a release in github to trigger the workflows. Once published:
    - this is now public and notifies subscribed users
    - makes the release "latest" in github
    - publishes artefacts and version-specific docker tags
    - publishes the docker `latest` tag variants
- [x] Check binary SHAs are correct on the release page
- [ ] Check "Container Verify" GitHub workflow has run successfully
- [x] Create besu-docs release - https://github.com/hyperledger/besu-docs/releases/new
  - Copy release notes from besu
  - If publishing the release in github doesn't automatically trigger this workflow, then manually run https://github.com/hyperledger/besu-docs/actions/workflows/update-version.yml
- [x] Create homebrew release - ❌ run GHA workflow directly https://github.com/hyperledger/homebrew-besu/actions/workflows/update-version.yml
- [x] Delete the burn-in nodes (unless required for further analysis eg performance)
- [x] Social announcements

**Comment by garyschulte** [comment]
FYI, running the homebrew GHA workflow silently fails:

```
Create Pull Request [permission needed]
Run gh pr create --base main --title "Update Besu version 24.8.0" --body "Besu version update to 24.8.0" || {
  gh pr create --base main --title "Update Besu version [2](https://github.com/hyperledger/homebrew-besu/actions/runs/10461548865/job/28970113510#step:5:2)4.8.0" --body "Besu version update to 24.8.0" || {
    echo "Action does not have permission to create PRs. Ignoring..."
  }
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_TOKEN: ***
pull request create failed: GraphQL: GitHub Actions is not permitted to create or approve pull requests (createPullRequest)
Action does not have permission to create PRs. Ignoring...
```

**Comment by garyschulte** [comment]
bumpy, but published
